# Generated by Django 4.2.7 on 2024-03-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodel_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='shipping_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
