# Generated by Django 4.2.7 on 2024-03-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmodel_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='shipping_cost',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
