# Generated by Django 4.2.7 on 2024-03-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_chart_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
