# Generated by Django 4.2.7 on 2024-03-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_chart_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='time',
        ),
    ]
